- CI: make sure XCUITest dsyms are always uploaded - CI: add release creation to sentry CLI script for main branch runs

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -213,6 +213,26 @@ jobs:
           
           ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH" 2>&1 >/dev/null)
           ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH_FRAMEWORK" 2>&1 >/dev/null)
+
+          if [ ! $? -eq 0 ]; then
+          echo "warning: sentry-cli - $ERROR"
+          fi
+
+      # Manually create release for sentry if running on /main
+      - name: Create release on sentry
+        if: github.ref == 'refs/heads/main'
+        run: |
+          export PATH=/usr/local/bin:$PATH
+          export SENTRY_ORG=kukai
+          export SENTRY_PROJECT=kukai-ios
+
+          app_bundle=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$PWD/build/Kukai-mobile.xcarchive/Info.plist")
+          app_version=$(/usr/libexec/PlistBuddy -c "Print :ApplicationProperties:CFBundleShortVersionString" $PWD/build/Kukai-mobile.xcarchive/Info.plist)
+          app_build=$(/usr/libexec/PlistBuddy -c "Print :ApplicationProperties:CFBundleVersion" $PWD/build/Kukai-mobile.xcarchive/Info.plist)
+          sentry_release_string="$app_bundle@$app_version+$app_build"
+
+          ERROR=$(sentry-cli releases new "$sentry_release_string")
+          ERROR=$(sentry-cli releases finalize "$sentry_release_string")
           
           if [ ! $? -eq 0 ]; then
           echo "warning: sentry-cli - $ERROR"
@@ -259,7 +279,7 @@ jobs:
 
       # Manually upload the dSYM's again incase any issues happen during XCUITests and we want to symbolicate them
       - name: Upload dSYM
-        if: ${{ success() }}
+        if: ${{ success() || failure() }}
         env:
           SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
         run: |
