- Update UI tests - re-enable github action - point to self hosted machine - wire up results parser and slack bot - comment out all tests bar first to test setup

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -9,12 +9,12 @@ on:
 jobs:
   deploy:
     name: Deploying to Testflight
-    runs-on: macos-15
-    #runs-on: self-hosted
+    #runs-on: macos-15
+    runs-on: self-hosted
     steps:
       - name: Select Xcode version
-        run: sudo xcode-select -s '/Applications/Xcode_16.app/Contents/Developer'
-        #run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
+        #run: sudo xcode-select -s '/Applications/Xcode_16.app/Contents/Developer'
+        run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
         
       - name: Checkout repository
         uses: actions/checkout@v4.1.1
@@ -100,42 +100,42 @@ jobs:
 
 
 
-      - name: Install Sentry CLI
-        if: ${{ success() }}
-        run: brew install getsentry/tools/sentry-cli
+      # - name: Install Sentry CLI
+      #   if: ${{ success() }}
+      #   run: brew install getsentry/tools/sentry-cli
 
-      - name: Upload dSYM
-        if: ${{ success() }}
-        env:
-          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-        run: |
-          export PATH=/usr/local/bin:$PATH
-          export SENTRY_ORG=kukai
-          export SENTRY_PROJECT=kukai-ios
-          export CUSTOM_DSYM_PATH="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Kukai Mobile.app.dSYM"
-          export CUSTOM_DSYM_PATH_FRAMEWORK="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Sodium.framework.dSYM"
+      # - name: Upload dSYM
+      #   if: ${{ success() }}
+      #   env:
+      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+      #   run: |
+      #     export PATH=/usr/local/bin:$PATH
+      #     export SENTRY_ORG=kukai
+      #     export SENTRY_PROJECT=kukai-ios
+      #     export CUSTOM_DSYM_PATH="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Kukai Mobile.app.dSYM"
+      #     export CUSTOM_DSYM_PATH_FRAMEWORK="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Sodium.framework.dSYM"
           
-          echo "CUSTOM_DSYM_PATH: $CUSTOM_DSYM_PATH"
-          echo "CUSTOM_DSYM_PATH_FRAMEWORK: $CUSTOM_DSYM_PATH_FRAMEWORK"
+      #     echo "CUSTOM_DSYM_PATH: $CUSTOM_DSYM_PATH"
+      #     echo "CUSTOM_DSYM_PATH_FRAMEWORK: $CUSTOM_DSYM_PATH_FRAMEWORK"
           
-          ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH" 2>&1 >/dev/null)
-          ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH_FRAMEWORK" 2>&1 >/dev/null)
+      #     ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH" 2>&1 >/dev/null)
+      #     ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH_FRAMEWORK" 2>&1 >/dev/null)
           
-          if [ ! $? -eq 0 ]; then
-          echo "warning: sentry-cli - $ERROR"
-          fi
+      #     if [ ! $? -eq 0 ]; then
+      #     echo "warning: sentry-cli - $ERROR"
+      #     fi
 
-      - name: Upload to TestFlight
-        if: ${{ success() }}
-        env:
-          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
-          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
-        run: xcrun altool --upload-app -t ios -f "build/Kukai Mobile.ipa" -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose
+      # - name: Upload to TestFlight
+      #   if: ${{ success() }}
+      #   env:
+      #     APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
+      #     APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
+      #   run: xcrun altool --upload-app -t ios -f "build/Kukai Mobile.ipa" -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose
 
 
-      - name: Commit new version number
-        if: ${{ github.ref != 'refs/heads/main' && success() }}
-        run: |
-          git add .
-          git commit -m "bump version"
-          git push origin HEAD
+      # - name: Commit new version number
+      #   if: ${{ github.ref != 'refs/heads/main' && success() }}
+      #   run: |
+      #     git add .
+      #     git commit -m "bump version"
+      #     git push origin HEAD
diff --git a/.github/workflows/nightly-uitests.yml b/.github/workflows/nightly-uitests.yml
--- a/.github/workflows/nightly-uitests.yml
+++ b/.github/workflows/nightly-uitests.yml
@@ -1,72 +1,82 @@
-# Commenting out for now as github actions can't seem to support running XCUITest. Runners are too low in resources.
-# Will run locally for now while consider other options
-#
-# name: Nightly UI Tests
-# on:
-#   push:
-#     branches:
-#       - feature/automated_tests
+name: Nightly UI Tests
+on:
+  push:
+    branches:
+      - develop
 
-# jobs:
-#   deploy:
-#     name: Run UI Tests
-#     runs-on: macos-13
-#     steps:
-#       - name: Select Xcode version
-#         run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer'
-    
-#       - name: Checkout repository
-#         uses: actions/checkout@v3.3.0
+jobs:
+  deploy:
+    name: Run UI Tests
+    runs-on: self-hosted
+    steps:
+      - name: Select Xcode version
+        run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
+        
+      - name: Checkout repository
+        uses: actions/checkout@v4.1.1
 
-#       - name: Setup Global Env
-#         run: |
-#           echo "SEED_PHRASE_1=${{ secrets.UITEST_SEED_PHRASE_1 }}" >> $GITHUB_ENV
-#           echo "SEED_PHRASE_PASSWORD=${{ secrets.UITEST_SEED_PHRASE_PASSWORD }}" >> $GITHUB_ENV
-#           echo "GMAIL_ADDRESS=${{ secrets.UITEST_GMAIL_ADDRESS }}" >> $GITHUB_ENV
-#           echo "GMAIL_PASSWORD=${{ secrets.UITEST_GMAIL_PASSWORD }}" >> $GITHUB_ENV
+      - name: Setup Global Env
+        run: |
+          echo "SEED_PHRASE_1=${{ secrets.UITEST_SEED_PHRASE_1 }}" >> $GITHUB_ENV
+          echo "SEED_PHRASE_PASSWORD=${{ secrets.UITEST_SEED_PHRASE_PASSWORD }}" >> $GITHUB_ENV
+          echo "GMAIL_ADDRESS=${{ secrets.UITEST_GMAIL_ADDRESS }}" >> $GITHUB_ENV
+          echo "GMAIL_PASSWORD=${{ secrets.UITEST_GMAIL_PASSWORD }}" >> $GITHUB_ENV
 
-#       - name: Build and run tests
-#         run: |
-#           xcodebuild -project "Kukai Mobile.xcodeproj" \
-#           -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" \
-#           -scheme "Kukai Mobile Beta" \
-#           -resultBundlePath TestResults \
-#           -configuration Beta \
-#           -archivePath $PWD/build/Kukai-mobile.xcarchive \
-#           clean \
-#           archive \
-#           test \
-#           SEED_PHRASE_1="$SEED_PHRASE_1" \
-#           SEED_PHRASE_PASSWORD="$SEED_PHRASE_PASSWORD" \
-#           GMAIL_ADDRESS="$GMAIL_ADDRESS" \
-#           GMAIL_PASSWORD="$GMAIL_PASSWORD"
-
-#       - name: Install Sentry CLI
-#         if: ${{ success() || failure() }}
-#         run: brew install getsentry/tools/sentry-cli
+      - name: Build and run tests
+        run: |
+          xcodebuild -project "Kukai Mobile.xcodeproj" \
+          -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 16,OS=18.5" \
+          -scheme "Kukai Mobile Beta" \
+          -resultBundlePath TestResults \
+          -configuration Beta \
+          -archivePath $PWD/build/Kukai-mobile.xcarchive \
+          clean \
+          archive \
+          test \
+          SEED_PHRASE_1="$SEED_PHRASE_1" \
+          SEED_PHRASE_PASSWORD="$SEED_PHRASE_PASSWORD" \
+          GMAIL_ADDRESS="$GMAIL_ADDRESS" \
+          GMAIL_PASSWORD="$GMAIL_PASSWORD"
       
-#       - name: Upload dSYM
-#         if: ${{ success() || failure() }}
-#         env:
-#           SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-#         run: |
-#           export PATH=/usr/local/bin:$PATH
-#           export SENTRY_ORG=kukai
-#           export SENTRY_PROJECT=kukai-ios
-#           export CUSTOM_DSYM_PATH="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Kukai Mobile.app.dSYM"
-#           export CUSTOM_DSYM_PATH_FRAMEWORK="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Sodium.framework.dSYM"
+      - name: Upload dSYM
+        if: ${{ success() || failure() }}
+        env:
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+        run: |
+          export PATH=/usr/local/bin:$PATH
+          export SENTRY_ORG=kukai
+          export SENTRY_PROJECT=kukai-ios
+          export CUSTOM_DSYM_PATH="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Kukai Mobile.app.dSYM"
+          export CUSTOM_DSYM_PATH_FRAMEWORK="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Sodium.framework.dSYM"
           
-#           echo "CUSTOM_DSYM_PATH: $CUSTOM_DSYM_PATH"
-#           echo "CUSTOM_DSYM_PATH_FRAMEWORK: $CUSTOM_DSYM_PATH_FRAMEWORK"
+          echo "CUSTOM_DSYM_PATH: $CUSTOM_DSYM_PATH"
+          echo "CUSTOM_DSYM_PATH_FRAMEWORK: $CUSTOM_DSYM_PATH_FRAMEWORK"
           
-#           ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH" 2>&1 >/dev/null)
-#           ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH_FRAMEWORK" 2>&1 >/dev/null)
+          ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH" 2>&1 >/dev/null)
+          ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH_FRAMEWORK" 2>&1 >/dev/null)
           
-#           if [ ! $? -eq 0 ]; then
-#           echo "warning: sentry-cli - $ERROR"
-#           fi
+          if [ ! $? -eq 0 ]; then
+          echo "warning: sentry-cli - $ERROR"
+          fi
 
-#       - uses: kishikawakatsumi/xcresulttool@v1.7.1
-#         if: ${{ success() || failure() }}
-#         with:
-#           path: TestResults.xcresult
+      - name: Upload xcresult file
+        uses: actions/upload-artifact@v4
+        with:
+          name: TestResults-${{ github.run_number }}.xcresult
+          path: TestResults.xcresult
+
+      - name: Parse results
+        id: xcresultparser_output
+        run: |
+          xcresultparser --output-format cli --failed-tests-only "TestResults.xcresult" >> $GITHUB_OUTPUT
+
+    #   - name: Share a file to that channel
+    #     uses: slackapi/slack-github-action@v2.0.0
+    #     with:
+    #         method: files.uploadV2
+    #         token: ${{ secrets.SLACK_BOT_TOKEN }}
+    #         payload: |
+    #             channel: ${{ secrets.SLACK_CHANNEL_ID }}
+    #             initial_comment: "Automated UI test run complete\n\n${{steps.xcresultparser_output.outputs}}"
+    #             file: "TestResults.xcresult"
+    #             filename: "TestResults-${{ github.run_number }}.xcresult"
