CI: re-enable cert logic to see if it works now. And tweak xcresults parser output to be compatible with Github

diff --git a/.github/workflows/nightly-uitests.yml b/.github/workflows/nightly-uitests.yml
--- a/.github/workflows/nightly-uitests.yml
+++ b/.github/workflows/nightly-uitests.yml
@@ -22,15 +22,11 @@ jobs:
           echo "SEED_PHRASE_PASSWORD=${{ secrets.UITEST_SEED_PHRASE_PASSWORD }}" >> $GITHUB_ENV
           echo "GMAIL_ADDRESS=${{ secrets.UITEST_GMAIL_ADDRESS }}" >> $GITHUB_ENV
           echo "GMAIL_PASSWORD=${{ secrets.UITEST_GMAIL_PASSWORD }}" >> $GITHUB_ENV
-
-    #echo "BUILD_CERTIFICATE_BASE64=${{ secrets.BUILD_CERTIFICATE_BASE64 }}" >> $GITHUB_ENV
-    #echo "P12_PASSWORD=${{ secrets.P12_PASSWORD }}" >> $GITHUB_ENV
-    #echo "KEYCHAIN_PASSWORD=${{ secrets.KEYCHAIN_PASSWORD }}" >> $GITHUB_ENV
-    #echo "BUILD_PROVISION_PROFILE_BASE64=${{ secrets.BUILD_PROVISION_PROFILE_BETA_BASE64 }}" >> $GITHUB_ENV
+          echo "BUILD_CERTIFICATE_BASE64=${{ secrets.BUILD_CERTIFICATE_BASE64 }}" >> $GITHUB_ENV
+          echo "P12_PASSWORD=${{ secrets.P12_PASSWORD }}" >> $GITHUB_ENV
+          echo "KEYCHAIN_PASSWORD=${{ secrets.KEYCHAIN_PASSWORD }}" >> $GITHUB_ENV
+          echo "BUILD_PROVISION_PROFILE_BASE64=${{ secrets.BUILD_PROVISION_PROFILE_BETA_BASE64 }}" >> $GITHUB_ENV
       
-
-
-
       # Upload Base64 copies of apple certs to github following these instructions: 
       # Note: Use app store distribution certs
       # https://docs.github.com/en/actions/guides/installing-an-apple-certificate-on-macos-runners-for-xcode-development
@@ -42,32 +38,29 @@ jobs:
       # BUILD_PROVISION_PROFILE_BETA_BASE64   = download "Kukai Mobile Beta Prov Dist App Store" from app store connect, copied with `base64 -i <file-path> | pbcopy`
       #
 
+      - name: Install the Apple certificate and provisioning profile
+        run: |
+          # create variables
+          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
+          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
+          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
 
-      
+          # import certificate and provisioning profile from secrets
+          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
+          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
 
-    #   - name: Install the Apple certificate and provisioning profile
-    #     run: |
-    #       # create variables
-    #       CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
-    #       PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
-    #       KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+          # create temporary keychain
+          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
 
-    #       # import certificate and provisioning profile from secrets
-    #       echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
-    #       echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
+          # import certificate to keychain
+          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+          security list-keychain -d user -s $KEYCHAIN_PATH
 
-    #       # create temporary keychain
-    #       security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-    #       security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
-    #       security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-
-    #       # import certificate to keychain
-    #       security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
-    #       security list-keychain -d user -s $KEYCHAIN_PATH
-
-    #       # apply provisioning profile
-    #       mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-    #       cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
+          # apply provisioning profile
+          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
 
       - name: Build and run tests
         run: |
@@ -84,40 +77,22 @@ jobs:
           SEED_PHRASE_PASSWORD="$SEED_PHRASE_PASSWORD" \
           GMAIL_ADDRESS="$GMAIL_ADDRESS" \
           GMAIL_PASSWORD="$GMAIL_PASSWORD"
-      
-      - name: Upload dSYM
-        if: ${{ success() || failure() }}
-        env:
-          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-        run: |
-          export PATH=/usr/local/bin:$PATH
-          export SENTRY_ORG=kukai
-          export SENTRY_PROJECT=kukai-ios
-          export CUSTOM_DSYM_PATH="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Kukai Mobile.app.dSYM"
-          export CUSTOM_DSYM_PATH_FRAMEWORK="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Sodium.framework.dSYM"
-          
-          echo "CUSTOM_DSYM_PATH: $CUSTOM_DSYM_PATH"
-          echo "CUSTOM_DSYM_PATH_FRAMEWORK: $CUSTOM_DSYM_PATH_FRAMEWORK"
-          
-          ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH" 2>&1 >/dev/null)
-          ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH_FRAMEWORK" 2>&1 >/dev/null)
-          
-          if [ ! $? -eq 0 ]; then
-          echo "warning: sentry-cli - $ERROR"
-          fi
 
       - name: Upload xcresult file
+        if: ${{ success() || failure() }}
         uses: actions/upload-artifact@v4
         with:
           name: TestResults-${{ github.run_number }}.xcresult
           path: TestResults.xcresult
 
       - name: Parse results
+        if: ${{ success() || failure() }}
         id: xcresultparser_output
         run: |
-          xcresultparser --output-format cli --failed-tests-only "TestResults.xcresult" >> $GITHUB_OUTPUT
+          xcresultparser --output-format txt --failed-tests-only "TestResults.xcresult" >> $GITHUB_OUTPUT
 
     #   - name: Share a file to that channel
+    #     if: ${{ success() || failure() }}
     #     uses: slackapi/slack-github-action@v2.0.0
     #     with:
     #         method: files.uploadV2
